/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class in_gov_uidai_auth_biometric_BIO_0005fAPI */

#ifndef _Included_in_gov_uidai_auth_biometric_BIO_0005fAPI
#define _Included_in_gov_uidai_auth_biometric_BIO_0005fAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_INIT_SUCCESSFUL
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_INIT_SUCCESSFUL 0L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_INIT_UNSUCCESSFUL
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_INIT_UNSUCCESSFUL 1L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_ERR_UNABLE_TO_CAPTURE
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_ERR_UNABLE_TO_CAPTURE 2L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_ERR_TOO_MANY_HANDLES
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_ERR_TOO_MANY_HANDLES 3L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_ERR_TIMEOUT_EXPIRED
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_ERR_TIMEOUT_EXPIRED 4L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_ERR_PURPOSE_NOT_SUPPORTED
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_ERR_PURPOSE_NOT_SUPPORTED 5L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATES_MATCH
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATES_MATCH 6L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATES_NOTMATCH
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATES_NOTMATCH 7L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_CAPTURE_SUCCESSFUL
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_CAPTURE_SUCCESSFUL 10L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_CAPTURE_UNSUCCESSFUL
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_CAPTURE_UNSUCCESSFUL 11L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_PURPOSE_VERIFICATION
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_PURPOSE_VERIFICATION 12L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_PURPOSE_ENROLLMENT
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_PURPOSE_ENROLLMENT 13L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATE_ISO_FORMAT
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATE_ISO_FORMAT 16L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATE_ANSI_FORMAT
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATE_ANSI_FORMAT 17L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_SAMPLE_QUALITY_GOOD
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_SAMPLE_QUALITY_GOOD 18L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_SAMPLE_QUALITY_POOR
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_SAMPLE_QUALITY_POOR 19L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATE_EXTRACT_UNSUCCESSFUL
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATE_EXTRACT_UNSUCCESSFUL 20L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATE_EXTRACT_SUCCESSFUL
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_TEMPLATE_EXTRACT_SUCCESSFUL 20L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_INIT_DLL_ALREADY_LOADED
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_INIT_DLL_ALREADY_LOADED 21L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_CONNECTED
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_CONNECTED 1L
#undef in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_DISCONNECTED
#define in_gov_uidai_auth_biometric_BIO_0005fAPI_BIO_API_DEVICE_DISCONNECTED 0L
/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    isDeviceConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_isDeviceConnected
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    captureSample
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_captureSample
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getSampleSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getSampleSize
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getSampleWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getSampleWidth
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getSampleHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getSampleHeight
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    extractTemplate
 * Signature: ([B[BIII)I
 */
JNIEXPORT jint JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_extractTemplate
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getTemplateSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getTemplateSize
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    compareTemplates
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_compareTemplates
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    createImage
 * Signature: ([B)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_createImage
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getDeviceMake
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getDeviceMake
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getDeviceModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getDeviceModel
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getDeviceSerialNumber
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getDeviceSerialNumber
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getSampleQuality
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getSampleQuality
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getExtracterVendor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getExtracterVendor
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getExtracterName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getExtracterName
  (JNIEnv *, jobject);

/*
 * Class:     in_gov_uidai_auth_biometric_BIO_0005fAPI
 * Method:    getExtracterVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_in_gov_uidai_auth_biometric_BIO_1API_getExtracterVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
